//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThietLapCauHinh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CauHinhEntities : DbContext
    {
        public CauHinhEntities()
            : base("name=CauHinhEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MB_PhanHe> MB_PhanHe { get; set; }
        public virtual DbSet<MB_Truong> MB_Truong { get; set; }
        public virtual DbSet<MB_Truong_PhanHe> MB_Truong_PhanHe { get; set; }
    }
}
