//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThietLapCauHinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class MB_PhanHe
    {
        public int Id { get; set; }
        public string MaPhanHe { get; set; }
        public string TenPhanHe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> IsHienThi { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
