//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ThietLapCauHinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class MB_Truong_PhanHe
    {
        public int Id { get; set; }
        public Nullable<int> IDTruong { get; set; }
        public Nullable<int> IDPhanHe { get; set; }
        public string Url { get; set; }
        public string Url_2 { get; set; }
        public string Url_3 { get; set; }
        public string UrlSocket { get; set; }
        public string SubAPI { get; set; }
        public string SubAPI_2 { get; set; }
        public string SubAPI_3 { get; set; }
        public string GhiChu { get; set; }
        public string Warning_RequireSurvey { get; set; }
        public string FeaturesRequireSurvey { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> VersionEgovAPI { get; set; }
        public string UrlPayment { get; set; }
        public Nullable<int> VersionStudentAPI { get; set; }
        public string WarningMessage { get; set; }
        public Nullable<bool> HasAds { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<int> VersionWeb { get; set; }
        public Nullable<bool> UseHTMLSalaryView { get; set; }
    }
}
